// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagos.Api.Data;

#nullable disable

namespace Pagos.Api.Migrations
{
    [DbContext(typeof(PagosDbContext))]
    partial class PagosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_CargoRecurrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DiaCobro")
                        .HasColumnType("int");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMensual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ProximoCobro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoCobro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("PAG_CargoRecurrente", (string)null);
                });

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_MetodoGuardado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsCreditoTienda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MarcaTarjeta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TokenIdOpenPay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ultimos4Digitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.ToTable("PAG_MetodoGuardado", (string)null);
                });

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsCargoRecurrente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<string>("IdTransaccionOpenPay")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MesesSinIntereses")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("PAG_Transaccion", (string)null);
                });

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_CargoRecurrente", b =>
                {
                    b.HasOne("Pagos.Domain.Entities.PAG_MetodoGuardado", "MetodoGuardado")
                        .WithMany("CargosRecurrentes")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoGuardado");
                });

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_Transaccion", b =>
                {
                    b.HasOne("Pagos.Domain.Entities.PAG_MetodoGuardado", "MetodoGuardado")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoGuardado");
                });

            modelBuilder.Entity("Pagos.Domain.Entities.PAG_MetodoGuardado", b =>
                {
                    b.Navigation("CargosRecurrentes");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
