// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordenes.Api.Data;

#nullable disable

namespace Ordenes.Api.Migrations
{
    [DbContext(typeof(OrdenesDbContext))]
    [Migration("20260518184404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Cat_EstadoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ORD_Cat_EstadoOrden", (string)null);
                });

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoLinea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("EsElectronica")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOrden");

                    b.ToTable("ORD_Detalle", (string)null);
                });

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("DescuentoAplicado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdDireccionEnvio")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("IdEstadoOrden");

                    b.ToTable("ORD_Orden", (string)null);
                });

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Detalle", b =>
                {
                    b.HasOne("Ordenes.Domain.Entities.ORD_Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Orden", b =>
                {
                    b.HasOne("Ordenes.Domain.Entities.ORD_Cat_EstadoOrden", "EstadoOrden")
                        .WithMany()
                        .HasForeignKey("IdEstadoOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoOrden");
                });

            modelBuilder.Entity("Ordenes.Domain.Entities.ORD_Orden", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
